const DATA = {
    configuracion: {
        gananciaGlobal: 40
    },
    productos: [
    {
      nombre: "Acrilico EQ50",
      codigo: "16472",
      costo: 1588,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Adhesivo en barra 21gr Keyroad",
      codigo: "16935",
      costo: 1166,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Adhesivo en barra 21gr Pegastick Util Uno",
      codigo: "13897",
      costo: 782,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Adhesivo en barra 21gr Sabonis",
      codigo: "14516",
      costo: 1648,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Adhesivo sintetico Keyroad 30ml tipo Voligoma",
      codigo: "14618",
      costo: 564,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Adhesivo sintetico Keyroad 50ml tipo Voligoma",
      codigo: "15606",
      costo: 697,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Afiche blanco",
      codigo: "10033",
      costo: 524,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Afiches de color",
      codigo: "10034",
      costo: 819,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Ametralladora a friccion",
      codigo: "255666",
      costo: 3588,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Ametralladora a friccion grande",
      codigo: "255667",
      costo: 5460,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Aprietapapeles binder 41mm x12",
      codigo: "12372",
      costo: 3471,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Aprietapapeles individual",
      codigo: "",
      costo: 290,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Armonica",
      codigo: "16966",
      costo: 1229,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Arrastre tortuga",
      codigo: "16728",
      costo: 3120,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Autito coleccion Hot Wheels",
      codigo: "15647",
      costo: 3120,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Autito coleccion metal",
      codigo: "16962",
      costo: 2496,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Auto policia",
      codigo: "17411",
      costo: 4095,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bandolera unisex",
      codigo: "",
      costo: 7100,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Barra silicona fina individual",
      codigo: "",
      costo: 507,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Barra silicona gruesa individual",
      codigo: "",
      costo: 1013,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Barra silicona gruesa x5",
      codigo: "10173",
      costo: 5063,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Barras silicona fina x10",
      codigo: "10172",
      costo: 5063,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bebote comer",
      codigo: "17445",
      costo: 21840,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bebote con mamadera y sonidos",
      codigo: "16406",
      costo: 29640,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Billeteras",
      codigo: "",
      costo: 5300,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Block dibujo N5 blanco 20 hojas",
      codigo: "13150",
      costo: 2332,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Boligrafo borrable Olami",
      codigo: "16281",
      costo: 1219,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Boligrafo fantasia goma",
      codigo: "255799",
      costo: 1027,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Boligrafo multicolor huellitas",
      codigo: "255798",
      costo: 1548,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Boligrafo multicolor minifood",
      codigo: "255797",
      costo: 1547,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Boligrafo roller gel brillo individual",
      codigo: "",
      costo: 523,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Boligrafo roller gel brillo x4",
      codigo: "17863",
      costo: 2092,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa acuario color liso 14x20",
      codigo: "",
      costo: 425,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa acuario color liso 22x30",
      codigo: "",
      costo: 542,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa acuario color liso 30x41",
      codigo: "",
      costo: 768,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa fantasia 14x20",
      codigo: "",
      costo: 551,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa fantasia 22x30",
      codigo: "",
      costo: 753,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa fantasia 30x41",
      codigo: "",
      costo: 1043,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa kraft papel madera 14x20 chica",
      codigo: "",
      costo: 337,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa kraft papel madera 14x40 vino",
      codigo: "",
      costo: 395,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa kraft papel madera 22x30 mediana",
      codigo: "",
      costo: 389,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa kraft papel madera 22x42 vino doble",
      codigo: "",
      costo: 445,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa kraft papel madera 30x41 grande",
      codigo: "",
      costo: 515,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa kraft papel madera 32x30 cuadrada",
      codigo: "",
      costo: 462,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Bolsa kraft papel madera 34x49 extragrande",
      codigo: "",
      costo: 575,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina comun",
      codigo: "",
      costo: 167,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina esmoquin individual",
      codigo: "",
      costo: 451,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina esmoquin x5",
      codigo: "13379",
      costo: 2253,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina gemas y diamantes individual",
      codigo: "",
      costo: 451,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina hexagonos individual",
      codigo: "",
      costo: 451,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina hexagonos x5",
      codigo: "15766",
      costo: 2253,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina spring flowers individual",
      codigo: "",
      costo: 371,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina spring flowers x9",
      codigo: "255638",
      costo: 3340,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina gemas y diamantes x5",
      codigo: "17242",
      costo: 2253,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Brillantina surtidas x5",
      codigo: "10337",
      costo: 833,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Carpeta base opaca A4",
      codigo: "15827",
      costo: 790,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Carpeta fantasía",
      codigo: "255949",
      costo: 3957,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Carpeta s/presphan con elástico habano A4",
      codigo: "16279",
      costo: 1236,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Carpetas fantasía nena y varón",
      codigo: "13075",
      costo: 5135,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartera Anto de nobuck",
      codigo: "",
      costo: 16100,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartera bandolera clara negra",
      codigo: "",
      costo: 16500,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartera bandolera Lucía",
      codigo: "",
      costo: 13600,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartera bandolera Paz",
      codigo: "",
      costo: 15700,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartera bandolera puff Romi",
      codigo: "",
      costo: 9500,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartera pechera de dama",
      codigo: "",
      costo: 14500,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartera Pilar",
      codigo: "",
      costo: 16100,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartón corrugado color",
      codigo: "11127",
      costo: 1817,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartón corrugado kraft",
      codigo: "11128",
      costo: 1166,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartulina blanca",
      codigo: "10591",
      costo: 363,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartulina color",
      codigo: "10592",
      costo: 498,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cartulina fantasía",
      codigo: "12493",
      costo: 742,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Chinches x 100 unidades",
      codigo: "13423",
      costo: 706,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cinta adhesiva 12x15",
      codigo: "17784",
      costo: 312,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cinta adhesiva 24x50",
      codigo: "16054",
      costo: 722,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cinta de embalar 48x50m",
      codigo: "255741",
      costo: 1420,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cinta de papel de color 24x20m",
      codigo: "255724",
      costo: 1480,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cinta de papel 24x40",
      codigo: "10619",
      costo: 2801,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Clip para abrochadora 21/6",
      codigo: "12891",
      costo: 1310,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Coche plegable",
      codigo: "16756",
      costo: 6143,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Corrector líquido 7ml Liggo",
      codigo: "17644",
      costo: 537,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cuaderno 42 hojas rayado azul tapa dura",
      codigo: "16517",
      costo: 2809,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cuaderno 48 hojas rayado rojo tapa dura",
      codigo: "12799",
      costo: 2809,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cuaderno Mis Hojas A5 fantasía 120 hojas",
      codigo: "15971",
      costo: 8666,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cuaderno Norpac A5 espiral fantasía",
      codigo: "255711",
      costo: 10460,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cuaderno Potosí tapa dura 42 hojas naranja",
      codigo: "12799",
      costo: 2809,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cuaderno rayado A4 con espiral",
      codigo: "16944",
      costo: 2509,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Cuadernos Norpac tamaño escolar 90 hojas",
      codigo: "",
      costo: 12788,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Dados",
      codigo: "10762",
      costo: 246,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Diario íntimo con candado 11x15cm",
      codigo: "17172",
      costo: 2789,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Dinosaurios de goma x2",
      codigo: "255668",
      costo: 7800,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Esfera telgopor N°10",
      codigo: "",
      costo: 1944,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Esfera telgopor N°12",
      codigo: "",
      costo: 2673,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Esfera telgopor N°4",
      codigo: "",
      costo: 139,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Esfera telgopor N°6",
      codigo: "",
      costo: 428,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Esfera telgopor N°8",
      codigo: "",
      costo: 869,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Esfera telgopor N°2",
      codigo: "",
      costo: 59,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Esmalte x2 Tiny",
      codigo: "16174",
      costo: 2145,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Estuche 411-16 Elegance Ball Point Retractable",
      codigo: "15924",
      costo: 6409,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Estuche de regalo E043 Set 538 + P922",
      codigo: "15709",
      costo: 3909,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Funda para cuadernos 19x24 individual",
      codigo: "",
      costo: 1219,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Funda para cuadernos 19x24 x2 unidades",
      codigo: "14530",
      costo: 2438,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Funda para cuadernos A4 individual",
      codigo: "",
      costo: 1782,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Funda para cuadernos A4 x2",
      codigo: "17883",
      costo: 3563,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "Funda para cuadernos escolares 50 hojas transparente",
      codigo: "14529",
      costo: 781,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "globo individual",
      codigo: "",
      costo: 116,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "globos surtidos x 50 party time",
      codigo: "",
      costo: 5767,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "globos x 50 naranja",
      codigo: "",
      costo: 5100,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "globos x50 negro",
      codigo: "",
      costo: 5100,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "goma dinos individual",
      codigo: "",
      costo: 379,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "goma eva",
      codigo: "10878",
      costo: 660,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "goma lapiz sabonis triangular x 50 unidades",
      codigo: "16947",
      costo: 18103,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "goma sabonis triangular individual",
      codigo: "",
      costo: 362,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "gomas dinos en barril x 12",
      codigo: "17793",
      costo: 4547,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "hebillas infantiles individual",
      codigo: "",
      costo: 830,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "hebillas infantiles x 15 surtidas",
      codigo: "",
      costo: 12450,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "juego 4 en linea",
      codigo: "16163",
      costo: 7800,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "labial esmalte y pinturitas",
      codigo: "14616",
      costo: 1716,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "lapicera bic trazo fino",
      codigo: "255564",
      costo: 1052,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "lapices de colores x12 largos filgo",
      codigo: "13733",
      costo: 2245,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "lapiz corrector 7ml filgo",
      codigo: "13107",
      costo: 623,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "lapiz de dibujo graduado sabonis individual",
      codigo: "",
      costo: 352,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "lapiz de dibujo graduado sabonis x12",
      codigo: "11034",
      costo: 4219,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "libreta fantasia mini 10x9cm basquet",
      codigo: "17963",
      costo: 1115,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "libreta fantasia mini 10x9cm gato",
      codigo: "17962",
      costo: 1115,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "libreta fantasia mini 10x9cm helado",
      codigo: "17960",
      costo: 1115,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "libreta fantasia mini 10x9cm tigre",
      codigo: "17961",
      costo: 1115,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "librito para colorear individual",
      codigo: "",
      costo: 292,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "marcador al agua filgo jumbo negro",
      codigo: "15050",
      costo: 751,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "marcador para pizarra filgo",
      codigo: "",
      costo: 1168,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "marcador para pizarra trabi",
      codigo: "",
      costo: 1168,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "masa modelar balde + accesorios",
      codigo: "17044",
      costo: 7492,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "mina 0,5 filgo",
      codigo: "11136",
      costo: 510,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "mochila matera negra con brillo mas juego chau lata",
      codigo: "",
      costo: 19200,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "mochila matera puff",
      codigo: "",
      costo: 12400,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "mochila virginia",
      codigo: "",
      costo: 18800,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "monederos puff",
      codigo: "",
      costo: 3500,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "muñeca con accesorios",
      codigo: "16147",
      costo: 3251,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "palito de brochette x 90 u",
      codigo: "12528",
      costo: 1025,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "palito de helado color x50",
      codigo: "12840",
      costo: 810,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "palito de helado natural x50",
      codigo: "11253",
      costo: 562,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "papel madera",
      codigo: "11280",
      costo: 312,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "plastilina x10 surtidas playcolor",
      codigo: "14741",
      costo: 1818,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "portaminas 0,5 sabonis",
      codigo: "11461",
      costo: 1260,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "promo de bolsas de regalo x 70 surtidas",
      codigo: "",
      costo: 31300,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "promo de libritos para colorear x 50",
      codigo: "",
      costo: 14600,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "recibo chico",
      codigo: "11504",
      costo: 1295,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "repuesto block 24hs rayado",
      codigo: "14420",
      costo: 1607,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "repuesto block 48 hojas rayadas",
      codigo: "14423",
      costo: 2963,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "resmas punax o chamex blancas 500 hojas 75gr",
      codigo: "17196",
      costo: 8728,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "separadores n3 con solapa 5 posic gadri",
      codigo: "17965",
      costo: 1667,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "set de geometría x 4 piezas 20cm benabi",
      codigo: "14541",
      costo: 832,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "set geometría 3 piezas 20cm",
      codigo: "12249",
      costo: 1349,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "set geometría 3 piezas acrilico",
      codigo: "14941",
      costo: 1420,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "set mostacillas tiny corazon",
      codigo: "255690",
      costo: 2340,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "silicona liquida sabonis 30ml",
      codigo: "14644",
      costo: 1179,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "silicona liquida sabonis x100ml",
      codigo: "15772",
      costo: 2694,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "sobre de fiesta",
      codigo: "",
      costo: 7000,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "stickers tamaño plancha 6cm x 15cm",
      codigo: "17593",
      costo: 329,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "tabla periodica",
      codigo: "15041",
      costo: 837,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "talonario chico alianza",
      codigo: "12707",
      costo: 1410,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "talonario grande",
      codigo: "12708",
      costo: 2814,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "tarjeteros dama",
      codigo: "",
      costo: 4700,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "tempera playcolor 8cc individual",
      codigo: "",
      costo: 187,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "tempera playcolor 8cc x10 unidades",
      codigo: "255610",
      costo: 1862,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "tempera playcolor pote 250gr",
      codigo: "",
      costo: 1420,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "temperas surtidas pastel 8cc x6",
      codigo: "14717",
      costo: 1031,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "tijera oficina 21cm mango plastico",
      codigo: "16600",
      costo: 1435,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "tijera olami soft grip 16,5cm",
      codigo: "15997",
      costo: 2488,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "voligoma 30ml",
      codigo: "10025",
      costo: 1999,
      ganancia: null,
      categoria: "Libreria",
    },
    {
      nombre: "voligoma 50ml",
      codigo: "16790",
      costo: 3217,
      ganancia: null,
      categoria: "Libreria",
    },
  ]
};
